export type Ticket = {
  id: string; reference: string; subject: string; category: string; status: 'open' | 'in_progress' | 'resolved';
  contact_email: string; created_at: string; updated_at: string;
  messages: { id: string; author: 'customer' | 'support'; text: string; created_at: string }[];
};
export const categories = ['Account', 'Billing', 'Devices', 'AI assistant', 'Reports', 'Other'];
export const guides = [
  { id: 'getting-started', category: 'Getting started', question: 'How do I get my first security score?', answer: 'Open Devices, tap +, and register a device. Record whether MFA, disk encryption and security updates are enabled, then review its access decision. Save it to calculate your inventory control score. Missing controls create review alerts automatically from your records.' },
  { id: 'score-method', category: 'Devices & reports', question: 'What does my security score measure?', answer: 'Each registered device has four equally weighted controls: MFA, encryption, current updates, and reviewed access. The score is the percentage recorded as complete across all devices. It is not a vulnerability scan or certification. Open incidents are shown separately and do not change this inventory score.' },
  { id: 'pro-billing', category: 'Billing', question: 'How do subscriptions and restore work?', answer: 'Open your membership from Overview to choose a monthly or annual plan. Prices come from RevenueCat. The preview uses clearly labeled simulated Test Store purchases with no real charges. Restore purchases checks the subscription on the current account. Real purchases require Apple or Google store setup.' },
  { id: 'cancel', category: 'Billing', question: 'How do I cancel my subscription?', answer: 'Open Membership → Manage subscription. Real subscriptions are managed through the store where you bought them. Cancellation stops future renewals; paid access generally remains until the end of the period. Test Store subscriptions are simulated and do not create real store charges or renewals.' },
  { id: 'access', category: 'Devices & reports', question: 'Does denying access block a device?', answer: 'No. Access decisions are recorded in your registry for tracking and review. This app does not currently enforce network access or scan endpoints. Change actual access through your identity, network or endpoint-management tools, then update the device record.' },
  { id: 'ai', category: 'AI assistant', question: 'What information does the AI assistant use?', answer: 'GPT-5.4 receives your question, recent conversation and a summary of your workspace controls and incidents. It provides guidance, not automatic actions. Do not enter passwords, private keys, classified or restricted data. Verify recommendations before applying changes.' },
  { id: 'reports', category: 'Devices & reports', question: 'How do I save and share a report?', answer: 'With Pro active, open Reports and generate a report after registering a device. Reports save a dated snapshot, sector context, control score and prioritized findings. Open a saved report and tap Share report. If sharing is unavailable, selectable report text is provided.' },
  { id: 'sectors', category: 'Workspaces', question: 'Can I use this for government or private-sector work?', answer: 'Open the workspace selector on Overview and choose personal, private or government. This context is included in reports and AI guidance. Government mode does not imply accreditation, isolated infrastructure, authorization to store classified data, or certified compliance.' },
  { id: 'login', category: 'Account', question: 'I cannot sign in. What should I check?', answer: 'Use the same sign-in method used to create the account. Existing email/password accounts are not automatically linked to Google. Check your email spelling and password; passwords must contain at least 10 characters. Expired sessions require sign-in again. You can submit a support request after signing in with a working account; self-service password recovery is not yet available.' },
  { id: 'support', category: 'Support', question: 'Where will I receive support replies?', answer: 'Your request and conversation are saved under My tickets. The app owner can read and respond through the protected Staff inbox. Updates appear in the app when you open or refresh a ticket. No email or push notifications are sent, no response time is promised, and this is not a staffed emergency-response service.' },
];